collections_dir: my_collections

collections:
    jobs:
        output: true
    degrees:
        output: true
    awards:
        output: true
    projects:
        output: true
    certificates:
        output: true
    categories:
        output: true

defaults:
    - scope:
        path: ""
        type: "jobs"
      values:
        layout: "job"
    - scope:
        path: ""
        type: "degrees"
      values:
        layout: "degree"
    - scope:
        path: ""
      values:
        layout: "default"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
        type: "certificates"
      values:
        layout: "certificate"
    - scope:
        path: ""
        type: "categories"
      values:
        layout: "category"
    - scope:
        path: "assets/images"
      values:
        image: true

baseurl: /portfolio
url: "https://pushkarkadam.github.io"

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
