collections_dir: my_collections

collections:
    jobs:
        output: true
    degrees:
        output: true
    awards:
        output: true

defaults:
    - scope:
        path: ""
        type: "jobs"
      values:
        layout: "job"
    - scope:
        path: ""
        type: "degrees"
      values:
        layout: "degree"
    - scope:
        path: ""
      values:
        layout: "default"

baseurl: /portfolio

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
